package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"codestandoff/backend/graph/model"
	"context"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, email string, password string, firstName *string, lastName *string) (*model.AuthPayload, error) {
	return r.Workflow.Signup(ctx, email, password, firstName, lastName)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.Workflow.Login(ctx, email, password)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return r.Workflow.Logout(ctx)
}

// CreateProblem is the resolver for the createProblem field.
func (r *mutationResolver) CreateProblem(ctx context.Context, title string, description string, difficulty string) (*model.Problem, error) {
	return r.Workflow.CreateProblem(ctx, title, description, difficulty)
}

// CreateMatch is the resolver for the createMatch field.
func (r *mutationResolver) CreateMatch(ctx context.Context, problemID string) (*model.Match, error) {
	return r.Workflow.CreateMatch(ctx, problemID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.Workflow.Me(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.Workflow.Users(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.Workflow.User(ctx, id)
}

// GetQuestions is the resolver for the getQuestions field.
func (r *queryResolver) GetQuestions(ctx context.Context, input model.GetQuestionsRequest) (*model.GetQuestionsResponse, error) {
	return r.Workflow.GetQuestions(ctx, input)
}

// Problems is the resolver for the problems field.
func (r *queryResolver) Problems(ctx context.Context) ([]*model.Problem, error) {
	return r.Workflow.Problems(ctx)
}

// Problem is the resolver for the problem field.
func (r *queryResolver) Problem(ctx context.Context, id string) (*model.Problem, error) {
	return r.Workflow.Problem(ctx, id)
}

// Matches is the resolver for the matches field.
func (r *queryResolver) Matches(ctx context.Context) ([]*model.Match, error) {
	return r.Workflow.Matches(ctx)
}

// Match is the resolver for the match field.
func (r *queryResolver) Match(ctx context.Context, id string) (*model.Match, error) {
	return r.Workflow.Match(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
